language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

before_script:
  - composer install

sudo: false

script:
  - ./vendor/bin/phpcs --standard=vendor/internations/kodierungsregelwerksammlung/ruleset.xml ./src/
  - ./vendor/bin/phpunit
